export const UP_DISTRICT_HINDI_NAMES: Record<string, string> = {
  "agra": "आगरा",
  "aligarh": "अलीगढ़",
  "ambedkar-nagar": "अंबेडकर नगर",
  "amethi": "अमेठी",
  "amroha": "अमरोहा",
  "auraiya": "औरैया",
  "ayodhya": "अयोध्या",
  "azamgarh": "आजमगढ़",
  "baghpat": "बागपत",
  "bagpat": "बागपत",
  "bahraich": "बहराइच",
  "ballia": "बलिया",
  "balrampur": "बलरामपुर",
  "banda": "बांदा",
  "barabanki": "बाराबंकी",
  "bareilly": "बरेली",
  "basti": "बस्ती",
  "bhadohi": "भदोही",
  "bijnor": "बिजनौर",
  "budaun": "बदायूं",
  "bulandshahr": "बुलंदशहर",
  "chandauli": "चंदौली",
  "chitrakoot": "चित्रकूट",
  "deoria": "देवरिया",
  "etah": "एटा",
  "etawah": "इटावा",
  "farrukhabad": "फर्रुखाबाद",
  "fatehpur": "फतेहपुर",
  "firozabad": "फिरोजाबाद",
  "gautam-buddha-nagar": "गौतम बुद्ध नगर",
  "ghaziabad": "गाजियाबाद",
  "ghazipur": "गाजीपुर",
  "gonda": "गोंडा",
  "gorakhpur": "गोरखपुर",
  "hamirpur": "हमीरपुर",
  "hapur": "हापुड़",
  "hardoi": "हरदोई",
  "hathras": "हाथरस",
  "jalaun": "जालौन",
  "jaunpur": "जौनपुर",
  "jhansi": "झांसी",
  "kannauj": "कन्नौज",
  "kanpur-dehat": "कानपुर देहात",
  "kanpur-nagar": "कानपुर नगर",
  "kasganj": "कासगंज",
  "kaushambi": "कौशांबी",
  "kheri": "लखीमपुर खीरी",
  "kushinagar": "कुशीनगर",
  "lalitpur": "ललितपुर",
  "lucknow": "लखनऊ",
  "maharajganj": "महराजगंज",
  "mahoba": "महोबा",
  "mainpuri": "मैनपुरी",
  "mathura": "मथुरा",
  "mau": "मऊ",
  "meerut": "मेरठ",
  "mirzapur": "मिर्जापुर",
  "moradabad": "मुरादाबाद",
  "muzaffarnagar": "मुजफ्फरनगर",
  "pilibhit": "पीलीभीत",
  "pratapgarh": "प्रतापगढ़",
  "prayagraj": "प्रयागराज",
  "raebareli": "रायबरेली",
  "rampur": "रामपुर",
  "saharanpur": "सहारनपुर",
  "sambhal": "संभल",
  "sant-kabir-nagar": "संत कबीर नगर",
  "shahjahanpur": "शाहजहांपुर",
  "shamli": "शामली",
  "shravasti": "श्रावस्ती",
  "siddharthnagar": "सिद्धार्थनगर",
  "sitapur": "सीतापुर",
  "sonbhadra": "सोनभद्र",
  "sultanpur": "सुल्तानपुर",
  "unnao": "उन्नाव",
  "varanasi": "वाराणसी"
};

export function getDistrictDisplayName(slug: string, fallbackName: string, locale: string): string {
  if (locale === "hi") {
    return UP_DISTRICT_HINDI_NAMES[slug.toLowerCase()] || fallbackName;
  }
  return fallbackName;
}
